### ISSUE TITLE
indentation is broken for method-definers with adjectives

### ISSUE THREAD

**Issue by hannesm** [dylan-lang/dylan-mode#17]
```
define compiler-sideways method print-method
    (stream :: <stream>, o :: <&method>, #key outputter)
end;
```

the body currently wants to be aligned to `method` + 2, whereas my intuition is it should be indented by 2 only...

**Comment by cgay** [comment]
This works perfectly for me.  "(stream" is indented 4 spaces and when I hit Enter at the end of that line I'm indented 2 spaces.  Going to close this.
