### ISSUE TITLE
Rename SLDB symbols

### ISSUE THREAD

**Issue by lassik** [dylan-lang/dylan-mode#43]
Ref #41 

DIME was forked from SLIME, and DIME currently defines symbols using SLIME's `sldb-` prefix. We should change the prefix.

In fact, SLIME itself is not following current Emacs Lisp namespace conventions since it uses `sldb` instead of `slime` as the prefix. Since we can start afresh with DIME we should follow the convetions.

I suggest changing `sldb` to `dime-debug`. The following would be the list of the new symbol names. Does it look reasonable?

* `dime-debug-insert-frame-call-to-repl`
* `dime-debug-hook`
* `dime-debug-initial-restart-limit`
* `dime-debug-condition`
* `dime-debug-restarts`
* `dime-debug-level`
* `dime-debug-backtrace-start-marker`
* `dime-debug-restart-list-start-marker`
* `dime-debug-continuations`
* `dime-debug-mode-syntax-table`
* `dime-debug-mode`
* `dime-debug-buffers`
* `dime-debug-find-buffer`
* `dime-debug-get-default-buffer`
* `dime-debug-get-buffer`
* `dime-debug-debugged-continuations`
* `dime-debug-setup`
* `dime-debug-activate`
* `dime-debug-reinitialize`
* `dime-debug-exit`
* `dime-debug-close-step-buffer`
* `dime-debug-insert-condition`
* `dime-debug-extras-hooks`
* `dime-debug-dispatch-extras`
* `dime-debug-insert-restarts`
* `dime-debug-insert-more-restarts`
* `dime-debug-frame-string`
* `dime-debug-frame-number`
* `dime-debug-frame-plist`
* `dime-debug-frame-restartable-p`
* `dime-debug-prune-initial-frames`
* `dime-debug-insert-frames`
* `dime-debug-compute-frame-face`
* `dime-debug-insert-frame`
* `dime-debug-fetch-more-frames`
* `dime-debug-restart-at-point`
* `dime-debug-frame-number-at-point`
* `dime-debug-var-number-at-point`
* `dime-debug-previous-frame-number`
* `dime-debug-frame-details-visible-p`
* `dime-debug-frame-region`
* `dime-debug-forward-frame`
* `dime-debug-backward-frame`
* `dime-debug-goto-last-frame`
* `dime-debug-beginning-of-backtrace`
* `dime-debug-recenter-region`
* `dime-debug-default-action`
* `dime-debug-default-action/mouse`
* `dime-debug-cycle`
* `dime-debug-end-of-backtrace`
* `dime-debug-fetch-all-frames`
* `dime-debug-show-source`
* `dime-debug-show-frame-source`
* `dime-debug-toggle-details`
* `dime-debug-show-frame-details`
* `dime-debug-frame-details`
* `dime-debug-insert-frame-variable-value-function`
* `dime-debug-insert-locals`
* `dime-debug-insert-frame-variable-value`
* `dime-debug-hide-frame-details`
* `dime-debug-disassemble`
* `dime-debug-eval-in-frame`
* `dime-debug-pprint-eval-in-frame`
* `dime-debug-inspect-in-frame`
* `dime-debug-inspect-var`
* `dime-debug-inspect-condition`
* `dime-debug-down`
* `dime-debug-up`
* `dime-debug-sugar-move`
* `dime-debug-details-up`
* `dime-debug-details-down`
* `dime-debug-quit`
* `dime-debug-continue`
* `dime-debug-abort`
* `dime-debug-invoke-restart`
* `dime-debug-invoke-restart-by-name`
* `dime-debug-break-with-default-debugger`
* `dime-debug-break-with-system-debugger`
* `dime-debug-step`
* `dime-debug-next`
* `dime-debug-out`
* `dime-debug-break-on-return`
* `dime-debug-break`
* `dime-debug-return-from-frame`
* `dime-debug-restart-frame`
* `dime-debug-recompile-frame-source`

**Comment by cgay** [comment]
Looks good to me.
